name: nike_shoes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_image.svg
    - assets/images/n1.png
    - assets/images/n2.png
    - assets/images/n3.png
    - assets/images/n4.png
    - assets/images/n5.png
    - assets/images/n6.png
